### PR TITLE
Support for %c, %ld, %llu, %lu and %u formats

### PR DESCRIPTION
**Pull request by piranna**
Add support for %c, %ld, %llu, %lu and %u formats

### CODE REVIEW

**Comment by piranna** [comment]
Any update on this?

**Comment by Lellansin** [comment]
Well, I'm sorry to reply late. I didn't have enough conscious to check my repo, cause  This is the first time PR to mine that I've met. In a sense, I'm very glad. I'll review/check before tonight. (I'm on duty now)

**Comment by piranna** [comment]
Thank you :-)

**Comment by Lellansin** [comment]
thx @piranna , I've merged it, and and published it in latest version.

**Comment by piranna** [comment]
:+1:

**Pull request merged**
